### ISSUE TITLE
NoSuchMethodException when adding dependency to POM

### ISSUE THREAD

**Issue by RowWill** [HanSolo/charts#33]
Note: NO code was added, this issue occurs when adding the dependency to the POM.

After adding the dependency
```
<dependency>
    <groupId>eu.hansolo.fx</groupId>
    <artifactId>charts</artifactId>
    <version>11.3</version>
    <type>pom</type>
</dependency>
```
to the POM the application fails to start.

Immediately upon start-up (even before spring kicks in) the following exception is thrown:
``` 
java.lang.NoSuchMethodError: 'com.sun.javafx.geom.transform.GeneralTransform3D com.sun.prism.d3d.D3DContext.getPerspectiveTransformNoClone()'
	at com.sun.prism.d3d.D3DContext.updateShaderTransform(D3DContext.java:290)
	at com.sun.prism.impl.ps.BaseShaderContext.checkState(BaseShaderContext.java:662)
	at com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderContext.java:583)
	at com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderContext.java:500)
	at com.sun.prism.impl.BaseGraphics.drawTexture(BaseGraphics.java:426)
	at com.sun.prism.impl.ps.BaseShaderGraphics.drawTexture(BaseShaderGraphics.java:139)
	at com.sun.javafx.sg.prism.NGImageView.renderContent(NGImageView.java:123)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGImageView.doRender(NGImageView.java:103)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:328)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
Once the application has loaded a `StackOverflowException` is eventually thrown as the above is recursively thrown.

**Comment by RowWill** [comment]
I do, the application is a fully working JavaFX application. I want to replace the JavaFX API charts with something more substantial.

When adding, I get the above issue, simply removing the dependency from the POM again solves the issue.

**Comment by RowWill** [comment]
I believe I've fixed the issue. I was adding the dependency to the top of the dependencies in the POM. It seem that this dependency must come after the declaration for JavaFX. I'll do some testing and report back. Sorry to waste your time

**Comment by RowWill** [comment]
Seems to be all good!
